server:
  port: 8083

spring:
  application:
    name: decky
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

jwt:
  secret: ${JWT_SECRET:default_secret_for_local_dev}